###############################################################
# DATA MAKEFILE
# Created on: 04/29/2016
###############################################################

include header.mk

#This is Example MODIFY accordingly

###################################
#T := target-create
#TARGETS += $T
#$T_SQLARGS :=	 
#$T_TYPES := nzsql

################################### 
#T := target-prepare
#TARGETS += $T
#$T_TYPES := rdata
#$T_RARGS := -q --vanilla
 
###################################
#T := target
#TARGETS += $T
#$T_TYPES := nzload
#$T_SQLARGS := -delim ','
#$T_TABLE := table
#$T_EXT := csv

include footer.mk